
Import ('SrcEnv')

localEnv = SrcEnv.Clone ();

localEnv.Append (CCFLAGS = Split ("-I./src -I./src/model -I./src/sheet"))

files = Split("""
	engine.c
	gnucap.c
	ngspice.c
	netlist.c
	""")

libgplot = localEnv.StaticLibrary('liboregano-engines', files)

